[package]
authors = ["Oliver Scherer <github35764891676564198441@oli-obk.de>", "Deadbeef <ent3rm4n@gmail.com>"]
edition = "2021"
name = "fixmeh"
version = "0.1.0"

[dependencies]
glob = "0.3.1"
linkify = "0.9.0"
maud = "0.24.0"
regex = "1.7.1"
