version: 2

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build


jobs:
  build:
    docker:
      - image: rust:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            rustfmt --version
            cargo fmt -- --check
      - run:
          name: Grep FIXME from rustc repo
          command: ./build.sh
      - run:
          name: Nightly Build
          command: |
            rustup update nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Test
          command: rustup run nightly cargo test
      - run:
          name: Upload rendered page
          command: ./deploy.sh build
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
