version: 2

jobs:
  build:
    docker:
      - image: rust:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            rustfmt --version
            cargo fmt -- --check
      - run:
          name: Grep FIXME from rustc repo
          command: ./build.sh
      - run:
          name: Nightly Build
          command: |
            rustup update nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Test
          command: rustup run nightly cargo test
      - run:
          name: Upload rendered page
          command: ./deploy.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
